# Generated by Django 3.2.5 on 2021-10-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionixx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='description',
        ),
    ]
